// OO jDREW Version 0.89
// Copyright (c) 2005 Marcel Ball
//
// This software is licensed under the LGPL (LESSER GENERAL PUBLIC LICENSE) License.
// Please see "license.txt" in the root directory of this software package for more details.
//
// Disclaimer: Please see disclaimer.txt in the root directory of this package.

package jdrew.oo.gui;

public class DebugConsole extends javax.swing.JFrame {

    /** Creates new form DebugConsole */
    public DebugConsole() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();

        setTitle("DebugConsole");
        setName("frm2");
        jScrollPane1.setViewportView(textPane);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.
                                                  HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.
                                                VERTICAL_SCROLLBAR_ALWAYS);
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        this.setBounds(1, 1, 600, 800);
    }

    public javax.swing.JTextPane getTextPane() {
        return textPane;
    }

    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textPane;
    // End of variables declaration

}
